remove older versions of elemental
rancher/ui-plugin-charts pull request #30
Opened 2023-11-03 16:03 UTC by aalves08

remove older versions of elemental

@jordojordo , will this sync automatically? meaning, will it remove these versions and generate the chart again?

2023-11-13 13:54 UTC, jordojordo commented
@aalves08 This will not remove the versions that have already been synced. But I'm curious why you would want to remove the older versions?

2023-11-13 15:46 UTC, aalves08 commented
It was a request from the backend developer I've talked with. Apparently it creates more havoc because they have to support multiple versions of the images for the OS iso build. They used to be stored in other places and now everything should be centralised like version `1.2.0`.

FYI @nwmac

2023-11-13 18:57 UTC, jordojordo commented
Makes sense, in that case you will need to remove all of the chart assets for those versions in `assets`, `charts`, and `extensions` - In addition the entries within for those versions will need to be removed from the `index.yaml`.

This will not remove the versions from the [releases](https://github.com/rancher/ui-plugin-charts/releases) or the [`ui-plugin-catalog` image](https://hub.docker.com/r/rancher/ui-plugin-catalog/tags) unfortunately, but we can release a patch version after this is merged which will not contain those versions.

2023-11-15 11:58 UTC, aalves08 commented
@jordojordo can you re-review this? I've removed all of the assets needed to do a proper cleanup.

2023-11-15 12:52 UTC, jordojordo requested changes

2023-11-15 12:52 UTC, jordojordo commented on assets/elemental/elemental-1.2.0.tgz
Should this be deleted?

2023-11-15 15:32 UTC, aalves08 commented on assets/elemental/elemental-1.2.0.tgz
No it shouldn't...

2023-11-15 15:40 UTC, jordojordo approved these changes

2023-11-15 15:57 UTC, merged